// INFO: Query key namming conventions
// INFO: RQ_YOUR-QUERY-KEY_CONTEXT
// INFO: "RQ_PROJECTS-BY-CLIENT_ADMIN"
// INFO: in above key: PROJECTS-BY-CLIENT is key and ADMIN is context where it is used

export const RQKeys = {
  CLIENTS: {
    "RQ_PROJECTS-BY-CLIENT_ADMIN": "RQ_PROJECTS-BY-CLIENT_ADMIN",
    "RQ_GET-CLIENT-BY-ID_ADMIN": "RQ_GET_CLIENT_BY_ID_ADMIN",
    "RQ_GET-ALL-CLIENTS_ADMIN": "RQ_GET-ALL-CLIENTS_ADMIN",
  },
  DASHBOARD: {
    RQ_STATS_ADMIN: "RQ_STATS_ADMIN",
  },
};
